# Generated by Django 5.2.1 on 2025-05-27 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0002_webtoonsview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webtoonsview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='webtoonsview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'webtoon'), name='unique_user_webtoon'),
        ),
        migrations.AddConstraint(
            model_name='webtoonsview',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address__isnull', False)), fields=('ip_address', 'webtoon'), name='unique_ip_webtoon'),
        ),
    ]
