# Generated by Django 5.2.1 on 2025-05-27 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0003_alter_webtoonsview_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedWebtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('original_url', models.URLField()),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('auto_sync', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_webtoons', to='webtoons.externalsource')),
                ('webtoon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_info', to='webtoons.webtoon')),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ImportedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_info', to='webtoons.chapter')),
                ('imported_webtoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_chapters', to='webtoons.importedwebtoon')),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('imported_chapters', models.PositiveIntegerField(default=0)),
                ('imported_webtoon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='webtoons.importedwebtoon')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='webtoons.externalsource')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
