# Generated by Django 5.2.1 on 2025-05-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0004_externalsource_importedwebtoon_importedchapter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-number']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='webtoons/thumbnails/'),
        ),
        migrations.AlterUniqueTogether(
            name='chapterimage',
            unique_together={('chapter', 'order')},
        ),
    ]
