# Generated by Django 5.2.1 on 2025-05-27 23:47

import webtoons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0005_alter_chapter_options_chapter_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='image',
            field=models.ImageField(upload_to=webtoons.models.chapter_image_path),
        ),
        migrations.AlterField(
            model_name='webtoon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=webtoons.models.webtoon_thumbnail_path),
        ),
    ]
